### PR TITLE
Added grid actions to export/import and updated readme

### PR DESCRIPTION
**Pull request by peterjaap**

### CODE REVIEW

**Comment by danslo** [comment]
Awesome, thanks for the PR!

**Comment by peterjaap** [comment]
You should be called danfast, not danslo!

**Comment by stay-different-digital** [comment]
@danslo could you also add a 1.1.1. tag?

**Comment by danslo** [comment]
Done!

**Comment by danslo** [comment]
Strangely, this feature works for me when I rightclick the new Export link, and copy paste it into my address bar. When I click Export directly, I'm redirected to the product page... weird.

**Comment by peterjaap** [comment]
I had the same thing! I chalked it up to something to do with redirects in
the browser cache, but apparently not.

Op wo 21 feb. 2018 om 19:59 schreef Daniel Sloof <notifications@github.com>:

**Comment by danslo** [comment]
Added it to existing product actions using a plugin. See d3bdf0e4bf1ce8ddaeb048ab83a883fac308db74.

Then it looks like this:
gnome-shell-screenshot-71uaez

Tagged as 1.2.0.

**Comment by peterjaap** [comment]
Yeah nice.

**Pull request merged**
